# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY stop_service.py /app

# Install any needed packages specified in requirements
# Install Docker SDK for Python
RUN pip install Flask docker jsonify

# Run the service
CMD ["python", "stop_service.py"]
