version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile.service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - my-network

  service2:
    build:
      context: .
      dockerfile: Dockerfile.service2
    ports:
      - "8200:8200"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
