# Dockerfile
FROM node:18  
# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Expose the port
EXPOSE 8200

# Command to run the app
CMD ["node", "service2.js"]
